# -*- coding: utf-8 -*-
"""vanshidalal_cappsule-assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_zBeiHWXK3iLDjcqPvshltIcmnTNQ78
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
 

master = pd.read_excel('master.xlsx')
test = pd.read_csv('test.csv')

print(test)

master.rename(columns={'S No.':'S_No','Product ID':'Product_ID','Item name':'Item_Name'},
inplace=True)
test.rename(columns={'S No.':'S_No','Item Name':'Item_Name'},inplace=True)
print(test)

master_df = pd.DataFrame(master)
test_df = pd.DataFrame(test)

test_df

master_df

extracted_col = master_df["Product_ID"]
output = test_df.join(extracted_col)
print(output)

data_with_product_id = pd.DataFrame(output) 
data_with_product_id.to_excel("output.xlsx")